/** try catch block
 * 
 * try{
 *   some line of code....
 * } catch(error) {
 *   console.log("error occured")
 * }
 */



const userName = "Bravo";

try{
    userFunction();
    console.log("Hey, Are you okay?");
} catch(error) {
    console.log("error ocurred");
}

console.log(userName);





